apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bundled-base
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Shockedshodan/gitops-deployments
    path: bundle
    targetRevision: Kustomized-deployments/HEAD
    directory:
      recurse: true
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: 
     prune: true 
     selfHeal: true 
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
