apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uc2-workload-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: uc2
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://glaciation-heu.github.io/glaciation-uc2-workload-service/helm-charts/
    chart: uc2-workload
    targetRevision: 0.*.*
    helm:
      valuesObject:
        ingressHostName: uc2-workload.integration
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
