apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mef-sog-uc1-ingress
  namespace: mef-sog-uc1-wl
  annotations:
    nginx.org/client-max-body-size: "1024m"
#    nginx.ingress.kubernetes.io/proxy-body-size: "1024m"
spec:
  ingressClassName: nginx
  rules:
    - host: mef-sog-uc1.integration
      http:
        paths:
          - backend:
              service:
                name: scheduled-client-entrypoint
                port:
                  number: 80
            path: /
            pathType: Prefix
