apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neo4j
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - chart: neo4j
      repoURL: https://neo4j.github.io/helm-charts/
      targetRevision: 5.*.*
      helm:
        values: |
          volumes.data.mode:
            defaultStorageClass
          neo4j.password:
            name: neo4j-password-secret
            key: password
          neo4j.user:
            name: neo4j-user-secret
            key: user
  destination:
    server: https://kubernetes.default.svc
    namespace: idmg
  syncPolicy:
    automated: 
     prune: true 
     selfHeal: true 
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
