apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-storage-service
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dkg-engine
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://glaciation-heu.github.io/glaciation-data-storage-service/helm-charts/
    chart: data-storage-service
    targetRevision: 0.*.*
    helm:
      valuesObject:
        ingressHostName: data-storage.integration
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
