apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ui-gateway
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: dkg-engine
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://glaciation-heu.github.io/ui_gateway/helm-charts
    chart: ui-gateway-server
    targetRevision: 0.*.*
  syncPolicy:
    automated:
     prune: true
     selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

