apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafdrop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://glaciation-heu.github.io/mef-sog-uc1/'
    targetRevision: 0.1.0
    helm:
      values: |
        server:
          port: 9000
          servlet:
            contextPath: /kafdrop
        service:
          annotations: {}
          type: NodePort
          port: 9000
          nodePort: 30010
        kafka:
          brokerConnect: kafka.kafka.svc.cluster.local:9092
    chart: kafdrop
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafdrop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
