apiVersion: v1
kind: Namespace
metadata:
  name: local-path-storage
  annotations:
      argocd.argoproj.io/hook: PreSync
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-path-provisioner-service-account
  namespace: local-path-storage
  annotations:
      argocd.argoproj.io/hook: PreSync