name: Build Kustomize Bundle
on:
    push:
        branches:
        - 'Kustomized-deployments'
        - 'main'
        paths: 
            - .github/**
            - overlays/**
            - base/**

jobs:
    kustomize:
        name: Build Kustomize Bundle
        runs-on: ubuntu-latest
        env: 
            CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
            CI_COMMIT_AUTHOR: Continuous Integration
        strategy:
            matrix:
                overlay:
                    - 'integration'
                    - 'UC2'
        steps:

        - id: check-branch-exists
          uses: GuillaumeFalourd/branch-exists@v1
          with:
            branch: 'deploy'


        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: 'Kustomized-deployments'
            fetch-depth: 0

        - name: Kustomize Build
          uses: karancode/kustomize-github-action@master
          with:
            kustomize_version: '5.4.0'
            kustomize_build_dir: 'overlays/${{ matrix.overlay }}'
            kustomize_comment: true
            kustomize_output_file: "bundle/${{ matrix.overlay }}/${{ matrix.overlay }}.yaml"
            token: ${{ github.token}}
          env:
            GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

        - if: steps.check-branch-exists.outputs.exists == 'true'
          run: echo 'deploy Branch exists'


        - name: GIT Commit Kustomize Build Artifacts
          if: github.event_name == 'push'
          run: |
            git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add bundle/${{ matrix.overlay }}/${{ matrix.overlay }}.yaml
            git commit -m "${{ env.CI_COMMIT_MESSAGE }} - ${{ matrix.overlay }}"
            git push origin deploy